version: '3'

services:
  database:
    image: postgres:10.7-alpine

  description:
    build: ''
    depends_on:
      - 'database'
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "1.5"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "8080:8080"
