version: '3'

services:
  db:
    image: postgres:10.7-alpine
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  description:
    image: hluu5/sdc:zillow-service
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "1.5"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "8080:8080"
    networks:
      - webnet
networks:
  webnet:

